# Generated by Django 5.0.6 on 2024-06-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=23)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
